services:
  moonlight-web:
    # Этот образ доступен на Docker Hub и работает без ошибок доступа
    image: ipeit/moonlight-chrome-wasmv2:latest
    container_name: moonlight-web
    restart: always
    ports:
      - "8080:80"
