services:
  moonlight-web:
    # Используем этот проверенный образ:
    image: moonlighstream/moonlight-chrome-wasmv2:latest
    container_name: moonlight-web
    restart: always
    ports:
      - "8080:80"
