services:
  moonlight-web:
    # Прописываем зеркало напрямую, чтобы Docker не искал на заблокированном Hub
    image: huecker.io/ipeit/moonlight-chrome-wasmv2:latest
    container_name: moonlight-web
    restart: always
    ports:
      - "8080:80"
