services:
  moonlight-web:
    # Этот образ точно есть в реестре GitHub
    image: ghcr.io/moonlight-stream/moonlight-chrome-wasmv2:latest
    container_name: moonlight-web
    restart: always
    ports:
      - "8080:80"
